services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - "POSTGRES_DB=raffle_db"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=test1234"
    networks:
      - redelocal

networks:
  redelocal:
